import numpy as np

eye = np.eye(39, dtype=np.half)

action_vector = {
    "ct_build_worker": eye[0],
    "ct_build_cart": eye[1],
    "ct_research": eye[2],
    "w_mn": eye[3],
    "w_me": eye[4],
    "w_ms": eye[5],
    "w_mw": eye[6],
    "w_mc": eye[7],
    "w_pillage": eye[8],
    "w_tnwood": eye[9],
    "w_tewood": eye[10],
    "w_tswood": eye[11],
    "w_twwood": eye[12],
    "w_tncoal": eye[13],
    "w_tecoal": eye[14],
    "w_tscoal": eye[15],
    "w_twcoal": eye[16],
    "w_tnuranium": eye[17],
    "w_teuranium": eye[18],
    "w_tsuranium": eye[19],
    "w_twuranium": eye[20],
    "w_build": eye[21],
    "c_mn": eye[22],
    "c_me": eye[23],
    "c_ms": eye[24],
    "c_mw": eye[25],
    "c_mc": eye[26],
    "c_tnwood": eye[27],
    "c_tewood": eye[28],
    "c_tswood": eye[29],
    "c_twwood": eye[30],
    "c_tncoal": eye[31],
    "c_tecoal": eye[32],
    "c_tscoal": eye[33],
    "c_twcoal": eye[34],
    "c_tnuranium": eye[35],
    "c_teuranium": eye[36],
    "c_tsuranium": eye[37],
    "c_twuranium": eye[38],
}
